web/router.ex
defmodule SL.Router do
  use SL.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Auth.Plugs.SetUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :app do
    plug Auth.Plugs.UserAuthenticated
  end

  scope "/", SL do
    pipe_through :browser # Use the default browser stack

    get "/", FeedController, :index

    get "/login",       AuthController, :index
    get "/auth/google", AuthController, :new
    get "/logout",      AuthController, :delete
  end

  scope "/", SL do
    pipe_through [:browser, :app]

    get "/books/start-new", BookController, :start_new
    resources "/books", BookController do
      resources "/book_copies", BookCopyController, only: [:new, :create, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SL do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule SL.LayoutView do
  use SL.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SL!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="<%= feed_path(@conn, :index) %>">Home</a></li>
            <li><%= link "Books", to: book_path(@conn, :index) %></li>
            <li><%= link "Logout", to: auth_path(@conn, :delete) %></li>
          </ul>
        </nav>

        <a href="<%= feed_path(@conn, :index) %>"><span class="logo"></span></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script>window.userToken = "<%= @user_token %>";</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/app_with_no_navigation.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello SL!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <a href="<%= feed_path(@conn, :index) %>"><span class="logo"></span></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>