web/router.ex
defmodule SL.Router do
  use SL.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Auth.Plugs.SetUser
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :app do
    plug Auth.Plugs.UserAuthenticated
  end

  scope "/", SL do
    pipe_through :browser # Use the default browser stack

    get "/", FeedController, :index

    get "/login",       AuthController, :index
    get "/auth/google", AuthController, :new
    get "/logout",      AuthController, :delete
  end

  scope "/", SL do
    pipe_through [:browser, :app]

    get "/books/start-new", BookController, :start_new
    resources "/books", BookController do
      resources "/book_copies", BookCopyController, only: [:new, :create, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SL do
  #   pipe_through :api
  # end
end

web/models/book.ex
defmodule SL.Book do
  use SL.Web, :model

  schema "books" do
    field :title, :string
    field :isbn, :string
    field :image_url, :string
    field :description, :string

    has_many :book_copies, SL.BookCopy

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :isbn, :image_url, :description])
    |> validate_required([:title, :isbn, :description])
    |> unique_constraint(:isbn, name: :books_isbn_index)
  end

  def with_book_copies(id) do
    q = from b in SL.Book,
      where: b.id == ^id,
      preload: [:book_copies]
    SL.Repo.one(q)
  end
end

web/controllers/book_controller.ex
defmodule SL.BookController do
  use SL.Web, :controller

  alias SL.Book

  def index(conn, _params) do
    books = Repo.all(Book)
    render(conn, "index.html", books: books)
  end

  def start_new(conn, _params) do
    render(conn, "start_new.html")
  end

  def new(conn, %{"isbn" => isbn}) do
    changeset =
      SL.Remote.Data.Book.get_data(isbn, %Book{isbn: isbn})
      |> Book.changeset()

    render(conn, "new.html", changeset: changeset)
  end

  def new(conn, _params) do
    changeset = Book.changeset(%Book{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"book" => book_params}) do
    changeset = Book.changeset(%Book{}, book_params)

    case Repo.insert(changeset) do
      {:ok, book} ->
        SL.Feed.Broadcast.new_book(book, book_path(conn, :show, book), conn.assigns.current_user)

        conn
        |> put_flash(:info, "Book created successfully.")
        |> redirect(to: book_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    book =
      Book
      |> Repo.get!(id)
      |> Repo.preload(:book_copies)

    render(conn, "show.html", book: book)
  end

  def edit(conn, %{"id" => id}) do
    book = Repo.get!(Book, id)
    changeset = Book.changeset(book)
    render(conn, "edit.html", book: book, changeset: changeset)
  end

  def update(conn, %{"id" => id, "book" => book_params}) do
    book = Repo.get!(Book, id)
    changeset = Book.changeset(book, book_params)

    case Repo.update(changeset) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book updated successfully.")
        |> redirect(to: book_path(conn, :show, book))
      {:error, changeset} ->
        render(conn, "edit.html", book: book, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    book = Repo.get!(Book, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(book)

    conn
    |> put_flash(:info, "Book deleted successfully.")
    |> redirect(to: book_path(conn, :index))
  end
end

web/views/book_view.ex
defmodule SL.BookView do
  use SL.Web, :view

  alias SL.Book

  def intro(book = %Book{description: description})
      when byte_size(description) > 0
  do
    book
    |> format_description
    |> List.first
    |> ensure_length(600)
  end

  defp ensure_length({:safe, [_, description, _]}, max_length) do
    case byte_size(description) > max_length do
      true ->
        description
        |> String.slice(0, max_length)
        |> (fn text -> text <> "..." end).()
      false ->
        description
    end
  end

  def intro(_),
  do: ""

  def format_description(%Book{description: nil}),
  do: ""

  def format_description(%Book{description: description}) do
    description
    |> String.split("\n")
    |> Enum.map(&String.strip(&1))
    |> Enum.filter(&(&1 != ""))
    |> Enum.map(&content_tag(:p, &1))
  end
end

web/templates/book/edit.html.eex
<h2>Edit book</h2>

<%= render "form.html", changeset: @changeset,
                        action: book_path(@conn, :update, @book) %>

<%= link "Cancel", to: book_path(@conn, :index) %>

web/templates/book/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :isbn, "ISBN", class: "control-label" %>
    <%= text_input f, :isbn, class: "form-control" %>
    <%= error_tag f, :isbn %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :image_url, "Image URL", class: "control-label" %>
    <%= text_input f, :image_url, class: "form-control" %>
    <%= error_tag f, :image_url %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control", rows: 20 %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/book/index.html.eex
<h2>Listing books</h2>

<%= for book <- @books do %>
  <div class="row">
    <div class="col-sm-3">
      <div class="thumbnail">
        <a href="<%= book_path(@conn, :show, book) %>">
          <img src="<%= book.image_url %>" alt="<%= book.title %>" />
        </a>
      </div>
    </div>
    <div class="col-sm-9">
      <h4><%= link book.title, to: book_path(@conn, :show, book) %></h4>
      <small class="text-muted"><%= book.isbn %></small>
      <p><%= intro(book) %></p>
    </div>
  </div>
<% end %>

<%= link "New book", to: book_path(@conn, :start_new) %>

web/templates/book/new.html.eex
<h2>New book</h2>

<%= render "form.html", changeset: @changeset,
                        action: book_path(@conn, :create) %>

<%= link "Cancel", to: book_path(@conn, :index) %>

web/templates/book/show.html.eex
<h3>
  <%= @book.title %> <br/>
  <small><%= @book.isbn %></small>
</h3>

<p>
  <div class="row">
    <div class="col-sm-12 col-md-3">
      <div class="thumbnail" style="margin-right: 20px; width: 142px;">
        <img src="<%= @book.image_url %>" alt="<%= @book.title %>">
      </div>
    </div>
    <div class="col-sm-12 col-md-9">
      <ul class="list-group">
        <%= for book_copy <- @book.book_copies do %>
          <li class="list-group-item">
            <%= link book_copy.code, to: book_book_copy_path(@conn, :show, @book, book_copy) %>
          </li>
        <% end %>
      </ul>
      <%= link "Add copy", to: book_book_copy_path(@conn, :new, @book) %>
    </div>
  </div>
  <%= format_description(@book) %>
</p>

<%= link "Back to list of books", to: book_path(@conn, :index) %>

web/templates/book/start_new.html.eex
<h2>New book</h2>

<form action="<%= book_path(@conn, :new) %>" method="get">
  <div class="form-group">
    <label class="control-label" for="isbn">ISBN</label>
    <input class="form-control" id="isbn" name="isbn" type="text">
  </div>

  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="Submit">
  </div>
</form>

<a href="<%= book_path(@conn, :index) %>">Cancel</a>